Fixed failing BWC tests when listing views unexpectedly works
ES 8.x returns 405 because it sees _query/views as invalid GET _query

ResponseException: method [GET], host [http://[::1]:38479], URI [/_query/views], status line [HTTP/1.1 405 Method Not Allowed]